# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 노빠구
description: > # this means to ignore newlines until "baseurl:"
  비전공자 노빠구 개발자 블르그~
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jsh612.github.io/"
permalink: :title/
full-url: "https://jsh612.github.io/" # the base hostname & protocol for your site

# CSS
sass:
  style: compressed

# Comments - Go to Disqus.com > sign up > get the short-name > insert it here
disqus-shortname:

# Form Settings
#
# Contact form can be enabled by getting an API key from https://getsimpleform.com/
simpleform-token:

# Redirect users after submitting the form
redirect-to: https://jsh612.github.io/

# Site version
version: 0.9

# Post date background - This will change the background of the post date and tag ribbon according to the theme. If set to no default green background will be used. If yes then the theme color scheme is used.

change-date-bg: no

# Build settings
markdown: kramdown

include: [_pages] # Includes files inside _pages directory [Do not remove this]

author:
  name: 노빠꾸
  image: 노빠꾸.png # The author image will be shown on the header. Place this image in /images/ folder.
  about: 비전공자 출신, 능동적 자기개발형 개발자
  email: nobacklife612@gmail.com # mailto: is automatically added

gems:
  - jekyll-seo-tag
  - jekyll-paginate
